import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import localFont from "next/font/local";
 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
 const spaceGrotesk=localFont({
  src:"./fonts/Space_Grotesk/static/SpaceGrotesk-SemiBold.ttf",
  variable:"--font-space-grotesk",
  
 })
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${spaceGrotesk.className} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
